# Generated by Django 3.2 on 2021-04-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='idDone',
            field=models.BooleanField(default=False),
        ),
    ]
