# Generated by Django 3.2 on 2021-04-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0002_todo_iddone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='idDone',
            new_name='isDone',
        ),
    ]
